# Generated by Django 4.2.3 on 2023-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=60)),
                ('numero_sucursal', models.CharField(max_length=5)),
                ('modelo_fiscal', models.CharField(max_length=40)),
                ('vencimiento_certificado_digital', models.DateField(blank=True, null=True)),
                ('punto_venta', models.IntegerField()),
                ('numero_serie', models.IntegerField()),
                ('fecha_cambio', models.DateField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=60)),
                ('numero_sucursal', models.CharField(max_length=5)),
                ('modelo_fiscal', models.CharField(max_length=40)),
                ('vencimiento_certificado_digital', models.DateField(blank=True, null=True)),
                ('punto_venta', models.IntegerField()),
                ('numero_serie', models.IntegerField()),
                ('fecha_cambio', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
